name: 'ci'
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - next
jobs:
  test-webpack4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint
      - run: yarn test

  test-webpack5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - run: yarn test:webpack5
